### ISSUE TITLE
Linux package fails

### ISSUE THREAD

**Issue by garagatyi** [TylerJewell/che-electron#1]
I tried **npm run pack:linux64** and got
```
> eclipse-che-desktop@1.0.0 pack:linux64 /home/gaal/workspace/che-electron
> electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico

sh: 1: electron-packager: not found

npm ERR! Linux 3.19.0-39-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "pack:linux64"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! eclipse-che-desktop@1.0.0 pack:linux64: `electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the eclipse-che-desktop@1.0.0 pack:linux64 script 'electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the eclipse-che-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico
npm ERR! You can get their info via:
npm ERR!     npm owner ls eclipse-che-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gaal/workspace/che-electron/npm-debug.log
```
Here is npm debug
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'pack:linux64' ]
2 info using npm@3.3.12
3 info using node@v5.2.0
4 verbose run-script [ 'prepack:linux64', 'pack:linux64', 'postpack:linux64' ]
5 info lifecycle eclipse-che-desktop@1.0.0~prepack:linux64: eclipse-che-desktop@1.0.0
6 silly lifecycle eclipse-che-desktop@1.0.0~prepack:linux64: no script for prepack:linux64, continuing
7 info lifecycle eclipse-che-desktop@1.0.0~pack:linux64: eclipse-che-desktop@1.0.0
8 verbose lifecycle eclipse-che-desktop@1.0.0~pack:linux64: unsafe-perm in lifecycle true
9 verbose lifecycle eclipse-che-desktop@1.0.0~pack:linux64: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/gaal/workspace/che-electron/node_modules/.bin:/home/gaal/local/bin:/usr/lib/maven/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/gaal/workspace/other/go/bin:/usr/lib/maven/bin:/home/gaal/local/bin:/usr/lib/maven/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/gaal/workspace/other/go/bin:/usr/lib/maven/bin:/home/gaal/local/bin:/usr/lib/maven/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/gaal/workspace/other/go/bin:/usr/lib/maven/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle eclipse-che-desktop@1.0.0~pack:linux64: CWD: /home/gaal/workspace/che-electron
11 silly lifecycle eclipse-che-desktop@1.0.0~pack:linux64: Args: [ '-c',
11 silly lifecycle   'electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico' ]
12 info lifecycle eclipse-che-desktop@1.0.0~pack:linux64: Failed to exec pack:linux64 script
13 verbose stack Error: eclipse-che-desktop@1.0.0 pack:linux64: `electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:88:13)
13 verbose stack     at ChildProcess.emit (events.js:173:7)
13 verbose stack     at maybeClose (internal/child_process.js:819:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
14 verbose pkgid eclipse-che-desktop@1.0.0
15 verbose cwd /home/gaal/workspace/che-electron
16 error Linux 3.19.0-39-generic
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "pack:linux64"
18 error node v5.2.0
19 error npm  v3.3.12
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error eclipse-che-desktop@1.0.0 pack:linux64: `electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico`
24 error spawn ENOENT
25 error Failed at the eclipse-che-desktop@1.0.0 pack:linux64 script 'electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the eclipse-che-desktop package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron-packager ./src "eclipse-che" --out=dist/ --platform=linux --arch=x64 --overwrite --version=0.36.1 --icon=assets/win/icon.ico
25 error You can get their info via:
25 error     npm owner ls eclipse-che-desktop
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by TylerJewell** [comment]
You don't have electron-packager installed.  do this.  I'll add to docs that this must be installed as a dependency.
npm install electron-packager -g
